#!/usr/bin/env bash
# tranfer file from client to server
# Requirment :
#    The path to the file to be transferred
#    The IP of the server we want to transfer the file to
#    The username scp connects with
#    The path to the SSH private key that scp uses

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"

if [ $? -eq 0]
then 
	echo "file was transferred succesfully"
else
	echo "file tranfer failed"
fi
