#!/usr/bin/env bash
#commands to install nginx on web server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

service nginx start
