#!/usr/bin/env bash
# config ngnix server to listen to port 80 short way

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
