#!/usr/bin/env bash
# Does the following:
#   Create a file /var/run/myscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT

sudo bash -c "echo $$ > /var/run/holbertonscript.pid"
trap 'echo "Y U no love me?!"' SIGINT
trap "sudo rm -f /var/run/holbertonscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/holbertonscript.pid; echo I hate the kill command; exit" SIGTERM

while :
do
	echo "To infinity and beyond"
	sleep 2

done
