#!/usr/bin/env bash
# print processes pid whose name contain the word bash along the name
# displays the PID, along with the process name, of
# processes whose name contain the word bash

pgrep -l bash
