#!/usr/bin/env bash
# Displays "To infinity and beyond" without a fixed end or duration, accompanied by.
# + a sleep 2 in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
done
