#!/usr/bin/env bash
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.
for p in {1..100}
do
	if [ $((p % 3)) == 0 ] && [ $((p % 5)) == 0 ]
	then 
		echo "FizzBuzz"
	elif [ $((p % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((p % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo $p
	fi
done
