#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School"
y=1
while [ $y -le 10 ]
do
	echo "Best School"
	if [ $y -eq 9 ]; then
	   echo "Hi"
	fi
	y=$((y+1))
done
