#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations
p=1
while [ $p -le 10 ]
do
	if [ $p -eq 4 ]
	then
		echo "bad luck"
	elif [ $p -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
  p=$((p + 1))
done
